name: "Windows RDP (Cloudflared)"
on:
  workflow_dispatch:
    inputs:
      password:
        description: '设置远程桌面密码'
        required: false
        default: 'P@ssw0rd!'
      timeout:
        description: '运行时间(分钟)'
        required: true
        default: '360' 