name: 'Setup Linux Desktop'
description: '配置 Linux 远程桌面环境'

inputs:
  desktop:
    description: '桌面环境类型'
    required: true
  browser:
    description: '浏览器类型'
    required: true
  password:
    description: '远程桌面密码'
    required: false
    default: 'P@ssw0rd!'

runs:
  using: "composite"
  steps:
    - name: 安装桌面环境和 XRDP
      shell: bash
      run: |
        # 更新系统
        sudo apt-get update
        
        # 安装桌面环境
        case ${{ inputs.desktop }} in
          "xfce")
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 xfce4-goodies
            ;;
          "mate")
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mate-desktop-environment-core
            ;;
          "lxde")
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -y lxde-core
            ;;
        esac
        
        # 安装选择的浏览器
        case ${{ inputs.browser }} in
          "firefox")
            sudo apt-get install -y firefox
            ;;
          "chrome")
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
            ;;
          "chromium")
            sudo apt-get install -y chromium-browser
            ;;
        esac
        
        # 安装 XRDP
        sudo apt-get install -y xrdp
        
        # 配置 XRDP
        sudo cp /etc/xrdp/xrdp.ini /etc/xrdp/xrdp.ini.bak
        sudo sed -i 's/3389/3390/g' /etc/xrdp/xrdp.ini
        sudo sed -i 's/max_bpp=32/max_bpp=128/g' /etc/xrdp/xrdp.ini
        sudo sed -i 's/xserverbpp=24/xserverbpp=30/g' /etc/xrdp/xrdp.ini
        echo xfce4-session > ~/.xsession
        
        # 设置用户
        sudo useradd -m -s /bin/bash runner || true
        echo "runner:${{ inputs.password }}" | sudo chpasswd
        sudo usermod -aG sudo runner
        
        # 启动服务
        sudo systemctl enable xrdp
        sudo systemctl restart xrdp 