name: 'Setup Windows RDP'
description: '配置 Windows 远程桌面'

inputs:
  password:
    description: '远程桌面密码'
    required: false
    default: 'P@ssw0rd!'

runs:
  using: "composite"
  steps:
    - name: 配置 RDP
      shell: pwsh
      run: |
        # 基础诊断信息
        Write-Host "==== 初始状态检查 ===="
        Write-Host "当前系统时间: $(Get-Date)"
        systeminfo | Select-String "OS Name", "OS Version"
        
        # 启用 RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        
        # 配置防火墙
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
        # 用户配置
        $Password = ConvertTo-SecureString "${{ inputs.password }}" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $Password 