name: Windows-RDP-Cloudflared

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
    - name: Download Cloudflared
      run: |
        Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"
    
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    
    - name: Create Tunnel
      run: |
        Write-Host "Starting Cloudflare Tunnel..."
        Write-Host "Using named tunnel configuration..."
        Write-Host "============================================"
        
        # 验证令牌
        if (-not $env:TUNNEL_TOKEN) {
            Write-Error "Tunnel token is not set!"
            exit 1
        }
        
        # 首先尝试登录
        .\cloudflared.exe tunnel login
        
        # 运行隧道并设置超时
        $job = Start-Job -ScriptBlock {
            .\cloudflared.exe tunnel --protocol auto --no-autoupdate run
        }
        
        # 等待隧道启动
        Start-Sleep -Seconds 10
        
        # 检查隧道状态
        $tunnelStatus = .\cloudflared.exe tunnel info
        Write-Host "Tunnel Status: $tunnelStatus"
        
        # 保持隧道运行
        Wait-Job $job
        Receive-Job $job
      env:
        TUNNEL_TOKEN: ${{ secrets.CLOUDFLARED_TOKEN }}