name: Windows-RDP-Cloudflared

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
    - name: Download Cloudflared
      run: |
        Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"
    
    - name: Enable RDP
      run: |
        # 启用 RDP 服务
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        
        # 配置 Network Level Authentication (Windows 11 需要)
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        
        # 启用防火墙规则
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
        # 启动 Remote Desktop 服务
        Start-Service TermService
        Set-Service TermService -StartupType Automatic
        
        # 配置用户和权限
        $Password = ConvertTo-SecureString "P@ssw0rd!" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $Password
        Enable-LocalUser -Name "runneradmin"
        
        # 添加到 Remote Desktop Users 组（使用错误处理）
        try {
            Add-LocalGroupMember -Group "Remote Desktop Users" -Member "runneradmin" -ErrorAction Stop
        } catch {
            Write-Host "Note: User already in Remote Desktop Users group"
        }
        
        # Windows 11 RDP 安全设置
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "SecurityLayer" -Value 2
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "MinEncryptionLevel" -Value 3
        
        # 启用远程桌面连接代理
        Set-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -name "fEnableTerminalServerDR" -Value 1
        
        # 验证 RDP 服务状态
        $rdpService = Get-Service TermService
        Write-Host "RDP Service Status: $($rdpService.Status)"
        
        # 等待服务完全启动
        Start-Sleep -Seconds 10
        
        # 显示配置信息
        Write-Host "==== 用户信息 ===="
        Get-LocalUser runneradmin | Select-Object Name,Enabled,LastLogon | Format-List
        
        Write-Host "==== 组成员身份 ===="
        Get-LocalGroupMember -Group "Administrators" | Where-Object {$_.Name -like "*runneradmin*"} | Format-List
        Get-LocalGroupMember -Group "Remote Desktop Users" | Where-Object {$_.Name -like "*runneradmin*"} | Format-List
        
        Write-Host "==== RDP 配置 ===="
        Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' | Select-Object UserAuthentication,SecurityLayer,MinEncryptionLevel
    
    - name: Create Tunnel
      run: |
        Write-Host "Starting Cloudflare Tunnel..."
        Write-Host "============================================"
        
        # 验证令牌
        if (-not $env:TUNNEL_TOKEN) {
            Write-Error "Tunnel token is not set!"
            exit 1
        }
        
        # 确保 RDP 端口可访问
        $testPort = Test-NetConnection -ComputerName localhost -Port 3389
        Write-Host "RDP Port Status: $($testPort.TcpTestSucceeded)"
        
        # 直接运行隧道
        Write-Host "Running tunnel with token..."
        .\cloudflared.exe tunnel run --token "$env:TUNNEL_TOKEN"
      env:
        TUNNEL_TOKEN: ${{ secrets.CLOUDFLARED_TOKEN }}