name: Linux RDP

on:
  workflow_dispatch:
    inputs:
      password:
        description: '远程桌面密码 (默认: P@ssw0rd!)'
        required: false
        type: string
        default: 'P@ssw0rd!'
      timeout:
        description: '运行时间 (60-360分钟)'
        required: true
        type: string
        default: '360'

jobs:
  rdp:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJson(inputs.timeout) }}
    
    steps:
      - name: 运行 Linux 桌面容器
        run: |
          docker run -d \
            --name linux-rdp \
            -p 3390:3389 \
            -e ROOT_PASSWORD=${{ inputs.password }} \
            -e USER=runner \
            -e PASSWORD=${{ inputs.password }} \
            danielguerra/ubuntu-xrdp

      - name: 配置 Cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          cloudflared tunnel run --token "$TUNNEL_TOKEN"
        env:
          TUNNEL_TOKEN: ${{ secrets.CLOUDFLARED_TOKEN }}