name: Remote Desktop Entry

on:
  workflow_dispatch:
    inputs:
      type:
        description: |
          选择远程桌面类型:

          Windows 远程桌面:
          [1] Windows + Cloudflared
              - 国外推荐
              - 稳定性好
          
          [2] Windows + Ngrok
              - 国内推荐
              - 配置简单
          
          Linux 远程桌面:
          [3] Linux + XFCE
              - 轻量快速
              - 推荐使用
          
          [4] Linux + MATE
              - Ubuntu 原生体验
              - 功能完整
          
          [5] Linux + LXDE
              - 超轻量级
              - 性能最佳
        required: true
        default: '1'
        type: choice
        options: ['1', '2', '3', '4', '5']
      os_type:
        description: |
          选择 Ubuntu 版本:

          推荐版本:
          [1] Ubuntu Latest
              - 最新版本
              - 推荐使用
          
          其他版本:
          [2] Ubuntu 22.04 LTS
              - 长期支持版
              - 稳定可靠
          
          [3] Ubuntu 20.04 LTS
              - 稳定版本
              - 兼容性好
        required: false
        default: '1'
        type: choice
        options: ['1', '2', '3']
      browser:
        description: |
          选择浏览器:

          推荐选择:
          [1] Firefox
              - 最稳定
              - 推荐使用
          
          其他选择:
          [2] Chrome
              - 功能完整
              - 需要下载
          
          [3] Chromium
              - 轻量快速
              - 开源版本
        required: false
        default: '1'
        type: choice
        options: ['1', '2', '3']
      password:
        description: |
          设置远程桌面密码:
          
          [默认] P@ssw0rd!
          [建议] 使用自定义强密码
          [注意] 请妥善保管密码
        required: false
        default: 'P@ssw0rd!'
      timeout:
        description: |
          设置运行时间:
          
          [范围] 60-360 分钟
          [默认] 360 分钟
          [注意] 超时后自动停止
        required: true
        default: '360'
        type: number

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.config.outputs.config }}
    steps:
      - id: config
        run: |
          # 配置转换
          case "${{ github.event.inputs.type }}" in
            "1"|"2") 
              echo "::set-output name=config::{\"type\":\"windows\",\"tunnel\":\"${{ github.event.inputs.type == '1' && 'cloudflared' || 'ngrok' }}\"}"
              ;;
            "3"|"4"|"5")
              echo "::set-output name=config::{
                \"type\":\"linux\",
                \"desktop\":\"${{ github.event.inputs.type == '3' && 'xfce' || github.event.inputs.type == '4' && 'mate' || 'lxde' }}\",
                \"os\":\"${{ github.event.inputs.os_type == '1' && 'ubuntu-latest' || github.event.inputs.os_type == '2' && 'ubuntu-22.04' || 'ubuntu-20.04' }}\",
                \"browser\":\"${{ github.event.inputs.browser == '1' && 'firefox' || github.event.inputs.browser == '2' && 'chrome' || 'chromium' }}\"
              }"
              ;;
          esac

  windows:
    needs: setup
    if: fromJson(needs.setup.outputs.config).type == 'windows'
    uses: ./.github/workflows/windows.yml
    with:
      tunnel: ${{ fromJson(needs.setup.outputs.config).tunnel }}
      password: ${{ github.event.inputs.password }}
      timeout: ${{ github.event.inputs.timeout }}
    secrets: inherit

  linux:
    needs: setup
    if: fromJson(needs.setup.outputs.config).type == 'linux'
    uses: ./.github/workflows/linux.yml
    with:
      os: ${{ fromJson(needs.setup.outputs.config).os }}
      desktop: ${{ fromJson(needs.setup.outputs.config).desktop }}
      browser: ${{ fromJson(needs.setup.outputs.config).browser }}
      password: ${{ github.event.inputs.password }}
      timeout: ${{ github.event.inputs.timeout }}
    secrets: inherit