name: Remote Desktop Entry

on:
  workflow_dispatch:
    inputs:
      type:
        description: |
          选择远程桌面类型:
          1 = Windows + Cloudflared (国外推荐)
          2 = Windows + Ngrok (国内推荐)
          3 = Linux + XFCE (轻量快速，推荐)
          4 = Linux + MATE (Ubuntu 原生体验)
          5 = Linux + LXDE (超轻量，性能最佳)
        required: true
        default: '1'
        type: choice
        options: ['1', '2', '3', '4', '5']
      os_type:
        description: |
          Ubuntu 版本选择 (仅Linux选项有效):
          1 = Ubuntu Latest (推荐)
          2 = Ubuntu 22.04
          3 = Ubuntu 20.04
        required: false
        default: '1'
        type: choice
        options: ['1', '2', '3']
      browser:
        description: |
          浏览器选择 (仅Linux选项有效):
          1 = Firefox (推荐，最稳定)
          2 = Chrome (需要额外下载)
          3 = Chromium (轻量级选择)
        required: false
        default: '1'
        type: choice
        options: ['1', '2', '3']
      password:
        description: '设置远程桌面密码'
        required: false
        default: 'P@ssw0rd!'
      timeout:
        description: '运行时间(分钟, 范围60-360)'
        required: true
        default: '360'
        type: number

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.config.outputs.config }}
    steps:
      - id: config
        run: |
          # 配置转换
          case "${{ github.event.inputs.type }}" in
            "1"|"2") 
              echo "::set-output name=config::{\"type\":\"windows\",\"tunnel\":\"${{ github.event.inputs.type == '1' && 'cloudflared' || 'ngrok' }}\"}"
              ;;
            "3"|"4"|"5")
              echo "::set-output name=config::{
                \"type\":\"linux\",
                \"desktop\":\"${{ github.event.inputs.type == '3' && 'xfce' || github.event.inputs.type == '4' && 'mate' || 'lxde' }}\",
                \"os\":\"${{ github.event.inputs.os_type == '1' && 'ubuntu-latest' || github.event.inputs.os_type == '2' && 'ubuntu-22.04' || 'ubuntu-20.04' }}\",
                \"browser\":\"${{ github.event.inputs.browser == '1' && 'firefox' || github.event.inputs.browser == '2' && 'chrome' || 'chromium' }}\"
              }"
              ;;
          esac

  windows:
    needs: setup
    if: fromJson(needs.setup.outputs.config).type == 'windows'
    uses: ./.github/workflows/windows.yml
    with:
      tunnel: ${{ fromJson(needs.setup.outputs.config).tunnel }}
      password: ${{ github.event.inputs.password }}
      timeout: ${{ github.event.inputs.timeout }}
    secrets: inherit

  linux:
    needs: setup
    if: fromJson(needs.setup.outputs.config).type == 'linux'
    uses: ./.github/workflows/linux.yml
    with:
      os: ${{ fromJson(needs.setup.outputs.config).os }}
      desktop: ${{ fromJson(needs.setup.outputs.config).desktop }}
      browser: ${{ fromJson(needs.setup.outputs.config).browser }}
      password: ${{ github.event.inputs.password }}
      timeout: ${{ github.event.inputs.timeout }}
    secrets: inherit