name: Windows RDP

on:
  workflow_call:
    inputs:
      tunnel:
        description: |
          隧道类型
          选项: cloudflared, ngrok
        required: true
        type: string
      password:
        description: |
          远程桌面密码
          默认: P@ssw0rd!
        required: false
        type: string
        default: 'P@ssw0rd!'
      timeout:
        description: |
          运行时间(分钟)
          范围: 60-360
        required: true
        type: string
        default: '360'

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: ${{ fromJson(inputs.timeout) }}
    steps:
      - uses: actions/checkout@v2
      
      # 复用的 Windows 配置步骤
      - name: Configure Windows
        uses: ./.github/actions/windows-setup
        with:
          password: ${{ inputs.password }}
      
      # 根据选择的隧道类型执行不同的操作
      - if: inputs.tunnel == 'cloudflared'
        name: Setup Cloudflared
        uses: ./.github/actions/cloudflared-tunnel
        
      - if: inputs.tunnel == 'ngrok'
        name: Setup Ngrok
        uses: ./.github/actions/ngrok-tunnel